/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package checkinn.view;

/**
 *
 * @author ACEWR
 */
public class AdminBookingHistory extends javax.swing.JFrame {

    /**
     * Creates new form AdminBookingHistory
     */
    public AdminBookingHistory() {
        initComponents();
        setTitle("Admin Booking History | CheckInn");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        DoubleViewInvoiceButton = new javax.swing.JButton();
        DoubleRoomLabel = new javax.swing.JLabel();
        DoubleRoomClient = new javax.swing.JLabel();
        DoubleCancelButton = new javax.swing.JButton();
        BookingHistoryLabel = new javax.swing.JLabel();
        CheckedInClientLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        CheckInnLogoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ExecutiveSuiteViewInvoiceButton = new javax.swing.JButton();
        ExecutiveSuiteLabel = new javax.swing.JLabel();
        ExecutiveSuiteRoomClient = new javax.swing.JLabel();
        ExecutiveSuiteCancelButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        SingleViewInvoiceButton = new javax.swing.JButton();
        SingleRoomLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        SingleRoomClient = new javax.swing.JLabel();
        SingleCancelButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        AdminDashboardButton = new javax.swing.JButton();
        AdminBookingHistoryButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AdminClientButton = new javax.swing.JButton();
        AdminReviewButton = new javax.swing.JButton();
        AccomodationLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        DeluxeViewInvoiceButton = new javax.swing.JButton();
        DeluxeRoomLabel = new javax.swing.JLabel();
        DeluxeRoomClient = new javax.swing.JLabel();
        DeluxeCancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(168, 214, 204));

        DoubleViewInvoiceButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DoubleViewInvoiceButton.setText("View Invoice");
        DoubleViewInvoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoubleViewInvoiceButtonActionPerformed(evt);
            }
        });

        DoubleRoomLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DoubleRoomLabel.setText("Double");

        DoubleRoomClient.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DoubleRoomClient.setText("Client 2");

        DoubleCancelButton.setBackground(new java.awt.Color(255, 0, 0));
        DoubleCancelButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DoubleCancelButton.setForeground(new java.awt.Color(255, 255, 255));
        DoubleCancelButton.setText("Cancel");
        DoubleCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoubleCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(DoubleRoomLabel)
                .addGap(190, 190, 190)
                .addComponent(DoubleRoomClient, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(DoubleViewInvoiceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(DoubleCancelButton)
                .addGap(38, 38, 38))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoubleViewInvoiceButton)
                    .addComponent(DoubleRoomLabel)
                    .addComponent(DoubleRoomClient)
                    .addComponent(DoubleCancelButton))
                .addGap(18, 18, 18))
        );

        BookingHistoryLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        BookingHistoryLabel.setText("BOOKING HISTORY");

        CheckedInClientLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CheckedInClientLabel.setText("Checked In Client");

        jPanel2.setBackground(new java.awt.Color(113, 161, 161));

        CheckInnLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkinnlogo.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BoyWithStuff.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(CheckInnLogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 811, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(67, 67, 67))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(CheckInnLogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel4.setBackground(new java.awt.Color(168, 214, 204));

        ExecutiveSuiteViewInvoiceButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ExecutiveSuiteViewInvoiceButton.setText("View Invoice");
        ExecutiveSuiteViewInvoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecutiveSuiteViewInvoiceButtonActionPerformed(evt);
            }
        });

        ExecutiveSuiteLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ExecutiveSuiteLabel.setText("Executive Suite");

        ExecutiveSuiteRoomClient.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ExecutiveSuiteRoomClient.setText("-");

        ExecutiveSuiteCancelButton.setBackground(new java.awt.Color(255, 0, 0));
        ExecutiveSuiteCancelButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ExecutiveSuiteCancelButton.setForeground(new java.awt.Color(255, 255, 255));
        ExecutiveSuiteCancelButton.setText("Cancel");
        ExecutiveSuiteCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecutiveSuiteCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(ExecutiveSuiteLabel)
                .addGap(175, 175, 175)
                .addComponent(ExecutiveSuiteRoomClient, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(ExecutiveSuiteViewInvoiceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(ExecutiveSuiteCancelButton)
                .addGap(37, 37, 37))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExecutiveSuiteViewInvoiceButton)
                    .addComponent(ExecutiveSuiteLabel)
                    .addComponent(ExecutiveSuiteRoomClient)
                    .addComponent(ExecutiveSuiteCancelButton))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(168, 214, 204));

        SingleViewInvoiceButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SingleViewInvoiceButton.setText("View Invoice");
        SingleViewInvoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingleViewInvoiceButtonActionPerformed(evt);
            }
        });

        SingleRoomLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SingleRoomLabel.setText("Single");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        SingleRoomClient.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SingleRoomClient.setText("Client 1");

        SingleCancelButton.setBackground(new java.awt.Color(255, 0, 0));
        SingleCancelButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SingleCancelButton.setForeground(new java.awt.Color(255, 255, 255));
        SingleCancelButton.setText("Cancel");
        SingleCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingleCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(SingleRoomLabel)
                .addGap(175, 175, 175)
                .addComponent(jLabel14)
                .addGap(19, 19, 19)
                .addComponent(SingleRoomClient, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(SingleViewInvoiceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(SingleCancelButton)
                .addGap(41, 41, 41))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SingleRoomLabel)
                    .addComponent(jLabel14)
                    .addComponent(SingleRoomClient)
                    .addComponent(SingleViewInvoiceButton)
                    .addComponent(SingleCancelButton))
                .addGap(22, 22, 22))
        );

        jPanel7.setBackground(new java.awt.Color(61, 125, 125));

        AdminDashboardButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AdminDashboardButton.setText("Admin Dashboard");
        AdminDashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminDashboardButtonActionPerformed(evt);
            }
        });

        AdminBookingHistoryButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AdminBookingHistoryButton.setText("Booking history");
        AdminBookingHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminBookingHistoryButtonActionPerformed(evt);
            }
        });

        LogoutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/7124045_logout_icon(1).png"))); // NOI18N
        LogoutButton.setText("Logout");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconAdmin.png"))); // NOI18N
        jLabel11.setText("jLabel11");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconBkngHstry.png"))); // NOI18N

        AdminClientButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AdminClientButton.setText("Clients");
        AdminClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminClientButtonActionPerformed(evt);
            }
        });

        AdminReviewButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AdminReviewButton.setText("Client Reviews");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AdminDashboardButton)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(AdminBookingHistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AdminReviewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AdminClientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)))
                .addGap(0, 49, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel2))
                .addGap(41, 41, 41)
                .addComponent(AdminDashboardButton)
                .addGap(18, 18, 18)
                .addComponent(AdminBookingHistoryButton)
                .addGap(18, 18, 18)
                .addComponent(AdminClientButton)
                .addGap(18, 18, 18)
                .addComponent(AdminReviewButton)
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addGap(66, 66, 66)
                .addComponent(LogoutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AccomodationLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AccomodationLabel.setText("Accomodation");

        jPanel5.setBackground(new java.awt.Color(168, 214, 204));

        DeluxeViewInvoiceButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeluxeViewInvoiceButton.setText("View Invoice");
        DeluxeViewInvoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeluxeViewInvoiceButtonActionPerformed(evt);
            }
        });

        DeluxeRoomLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeluxeRoomLabel.setText("Deluxe");

        DeluxeRoomClient.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeluxeRoomClient.setText("-");

        DeluxeCancelButton.setBackground(new java.awt.Color(255, 0, 0));
        DeluxeCancelButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeluxeCancelButton.setForeground(new java.awt.Color(255, 255, 255));
        DeluxeCancelButton.setText("Cancel");
        DeluxeCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeluxeCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(DeluxeRoomLabel)
                .addGap(198, 198, 198)
                .addComponent(DeluxeRoomClient, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(DeluxeViewInvoiceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(DeluxeCancelButton)
                .addGap(37, 37, 37))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeluxeViewInvoiceButton)
                    .addComponent(DeluxeRoomLabel)
                    .addComponent(DeluxeRoomClient)
                    .addComponent(DeluxeCancelButton))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(341, 341, 341)
                            .addComponent(AccomodationLabel)
                            .addGap(186, 186, 186)
                            .addComponent(CheckedInClientLabel))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(256, 256, 256)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(256, 256, 256)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(BookingHistoryLabel)
                                    .addGap(432, 432, 432))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24))))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BookingHistoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CheckedInClientLabel)
                            .addComponent(AccomodationLabel))
                        .addGap(41, 41, 41)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DoubleViewInvoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoubleViewInvoiceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoubleViewInvoiceButtonActionPerformed

    private void ExecutiveSuiteViewInvoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExecutiveSuiteViewInvoiceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExecutiveSuiteViewInvoiceButtonActionPerformed

    private void AdminDashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminDashboardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminDashboardButtonActionPerformed

    private void AdminBookingHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBookingHistoryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminBookingHistoryButtonActionPerformed

    private void DeluxeViewInvoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeluxeViewInvoiceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeluxeViewInvoiceButtonActionPerformed

    private void SingleViewInvoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingleViewInvoiceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SingleViewInvoiceButtonActionPerformed

    private void SingleCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingleCancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SingleCancelButtonActionPerformed

    private void DoubleCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoubleCancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoubleCancelButtonActionPerformed

    private void DeluxeCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeluxeCancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeluxeCancelButtonActionPerformed

    private void ExecutiveSuiteCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExecutiveSuiteCancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExecutiveSuiteCancelButtonActionPerformed

    private void AdminClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminClientButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminClientButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminBookingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminBookingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminBookingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminBookingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminBookingHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccomodationLabel;
    private javax.swing.JButton AdminBookingHistoryButton;
    private javax.swing.JButton AdminClientButton;
    private javax.swing.JButton AdminDashboardButton;
    private javax.swing.JButton AdminReviewButton;
    private javax.swing.JLabel BookingHistoryLabel;
    private javax.swing.JLabel CheckInnLogoLabel;
    private javax.swing.JLabel CheckedInClientLabel;
    private javax.swing.JButton DeluxeCancelButton;
    private javax.swing.JLabel DeluxeRoomClient;
    private javax.swing.JLabel DeluxeRoomLabel;
    private javax.swing.JButton DeluxeViewInvoiceButton;
    private javax.swing.JButton DoubleCancelButton;
    private javax.swing.JLabel DoubleRoomClient;
    private javax.swing.JLabel DoubleRoomLabel;
    private javax.swing.JButton DoubleViewInvoiceButton;
    private javax.swing.JButton ExecutiveSuiteCancelButton;
    private javax.swing.JLabel ExecutiveSuiteLabel;
    private javax.swing.JLabel ExecutiveSuiteRoomClient;
    private javax.swing.JButton ExecutiveSuiteViewInvoiceButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton SingleCancelButton;
    private javax.swing.JLabel SingleRoomClient;
    private javax.swing.JLabel SingleRoomLabel;
    private javax.swing.JButton SingleViewInvoiceButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getAdminDashboardButton() { return AdminDashboardButton; }
    public javax.swing.JButton getSingleViewInvoiceButton() { return SingleViewInvoiceButton; }
    public javax.swing.JButton getDoubleViewInvoiceButton() { return DoubleViewInvoiceButton; }
    public javax.swing.JButton getDeluxeViewInvoiceButton() { return DeluxeViewInvoiceButton; }
    public javax.swing.JButton getExecutiveSuiteViewInvoiceButton() { return ExecutiveSuiteViewInvoiceButton; }
    public javax.swing.JButton getSingleCancelButton() { return SingleCancelButton; }
    public javax.swing.JButton getDoubleCancelButton() { return DoubleCancelButton; }
    public javax.swing.JButton getDeluxeCancelButton() { return DeluxeCancelButton; }
    public javax.swing.JButton getExecutiveSuiteCancelButton() { return ExecutiveSuiteCancelButton; }
    public javax.swing.JButton getAdminClientButton() {
    return AdminClientButton;
}
    
    
        // --- SETTERS FOR BOOKING INFO ---
     public void setSingleBooking(boolean isBooked, String clientName) {
        SingleRoomClient.setText(isBooked ? clientName : "-");
        SingleViewInvoiceButton.setEnabled(isBooked);
        SingleCancelButton.setEnabled(isBooked);
    }
    
    public void setDoubleBooking(boolean isBooked, String clientName) {
        DoubleRoomClient.setText(isBooked ? clientName : "-");
        DoubleViewInvoiceButton.setEnabled(isBooked);
        DoubleCancelButton.setEnabled(isBooked);
    }
    
    public void setDeluxeBooking(boolean isBooked, String clientName) {
        DeluxeRoomClient.setText(isBooked ? clientName : "-");
        DeluxeViewInvoiceButton.setEnabled(isBooked);
        DeluxeCancelButton.setEnabled(isBooked);
    }
    
    public void setExecutiveSuiteBooking(boolean isBooked, String clientName) {
        ExecutiveSuiteRoomClient.setText(isBooked ? clientName : "-");
        ExecutiveSuiteViewInvoiceButton.setEnabled(isBooked);
        ExecutiveSuiteCancelButton.setEnabled(isBooked);
    }
    
    public javax.swing.JButton getLogoutButton() {
        return LogoutButton;
    }
    
    // --- METHOD TO RESET THE VIEW ---
   public void resetAllBookings() {
        setSingleBooking(false, null);
        setDoubleBooking(false, null);
        setDeluxeBooking(false, null);
        setExecutiveSuiteBooking(false, null);
    }

   public javax.swing.JButton getAdminReviewButton(){
    return AdminReviewButton;
}
   
}
