/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package checkinn.view;

import java.awt.event.ActionListener;
/**
 *
 * @author niss
 */
public class DashboardView extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public DashboardView() {
        initComponents();
                setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoPanel = new javax.swing.JPanel();
        CheckInnLogoLabel = new javax.swing.JLabel();
        SingleRoomPanel = new javax.swing.JPanel();
        SingleRoomDetailsButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DeluxeRoomPanel = new javax.swing.JPanel();
        DeluxeRoomDetailsButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ExecutiveSuitePanel = new javax.swing.JPanel();
        ExecutiveSuiteRoomDetailsButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        DoubleRoomPanel = new javax.swing.JPanel();
        DoubleRoomDetailsButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AccomodationLabel = new javax.swing.JLabel();
        AvailabilityLabel = new javax.swing.JLabel();
        DashboardMenuPanel = new javax.swing.JPanel();
        DashboardButton = new javax.swing.JButton();
        BookingHistoryButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        UserProfileLabel = new javax.swing.JLabel();
        UserNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LogoPanel.setBackground(new java.awt.Color(23, 194, 157));

        CheckInnLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkinnlogo.png"))); // NOI18N

        javax.swing.GroupLayout LogoPanelLayout = new javax.swing.GroupLayout(LogoPanel);
        LogoPanel.setLayout(LogoPanelLayout);
        LogoPanelLayout.setHorizontalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(CheckInnLogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(973, Short.MAX_VALUE))
        );
        LogoPanelLayout.setVerticalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(CheckInnLogoLabel)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        SingleRoomPanel.setBackground(new java.awt.Color(23, 194, 157));

        SingleRoomDetailsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SingleRoomDetailsButton.setText("Access Details");
        SingleRoomDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingleRoomDetailsButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Single");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Vacant");

        javax.swing.GroupLayout SingleRoomPanelLayout = new javax.swing.GroupLayout(SingleRoomPanel);
        SingleRoomPanel.setLayout(SingleRoomPanelLayout);
        SingleRoomPanelLayout.setHorizontalGroup(
            SingleRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SingleRoomPanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(256, 256, 256)
                .addComponent(SingleRoomDetailsButton)
                .addGap(32, 32, 32))
        );
        SingleRoomPanelLayout.setVerticalGroup(
            SingleRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SingleRoomPanelLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(SingleRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(SingleRoomDetailsButton))
                .addGap(33, 33, 33))
        );

        DeluxeRoomPanel.setBackground(new java.awt.Color(23, 194, 157));

        DeluxeRoomDetailsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeluxeRoomDetailsButton.setText("Access Details");
        DeluxeRoomDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeluxeRoomDetailsButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Deluxe");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Out of order");

        javax.swing.GroupLayout DeluxeRoomPanelLayout = new javax.swing.GroupLayout(DeluxeRoomPanel);
        DeluxeRoomPanel.setLayout(DeluxeRoomPanelLayout);
        DeluxeRoomPanelLayout.setHorizontalGroup(
            DeluxeRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeluxeRoomPanelLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(232, 232, 232)
                .addComponent(DeluxeRoomDetailsButton)
                .addGap(33, 33, 33))
        );
        DeluxeRoomPanelLayout.setVerticalGroup(
            DeluxeRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeluxeRoomPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(DeluxeRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeluxeRoomDetailsButton)
                    .addComponent(jLabel8))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeluxeRoomPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(27, 27, 27))
        );

        ExecutiveSuitePanel.setBackground(new java.awt.Color(23, 194, 157));

        ExecutiveSuiteRoomDetailsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ExecutiveSuiteRoomDetailsButton.setText("Access Details");
        ExecutiveSuiteRoomDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecutiveSuiteRoomDetailsButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Executive Suite");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Vacant");

        javax.swing.GroupLayout ExecutiveSuitePanelLayout = new javax.swing.GroupLayout(ExecutiveSuitePanel);
        ExecutiveSuitePanel.setLayout(ExecutiveSuitePanelLayout);
        ExecutiveSuitePanelLayout.setHorizontalGroup(
            ExecutiveSuitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExecutiveSuitePanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(252, 252, 252)
                .addComponent(ExecutiveSuiteRoomDetailsButton)
                .addGap(33, 33, 33))
        );
        ExecutiveSuitePanelLayout.setVerticalGroup(
            ExecutiveSuitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExecutiveSuitePanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(ExecutiveSuitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(ExecutiveSuiteRoomDetailsButton))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        DoubleRoomPanel.setBackground(new java.awt.Color(23, 194, 157));

        DoubleRoomDetailsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DoubleRoomDetailsButton.setText("Access Details");
        DoubleRoomDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoubleRoomDetailsButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Double");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Occupied");

        javax.swing.GroupLayout DoubleRoomPanelLayout = new javax.swing.GroupLayout(DoubleRoomPanel);
        DoubleRoomPanel.setLayout(DoubleRoomPanelLayout);
        DoubleRoomPanelLayout.setHorizontalGroup(
            DoubleRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DoubleRoomPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(244, 244, 244)
                .addComponent(DoubleRoomDetailsButton)
                .addGap(32, 32, 32))
        );
        DoubleRoomPanelLayout.setVerticalGroup(
            DoubleRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoubleRoomPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(DoubleRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(DoubleRoomDetailsButton))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        AccomodationLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AccomodationLabel.setText("Accomodation");

        AvailabilityLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AvailabilityLabel.setText("Availability");

        DashboardMenuPanel.setBackground(new java.awt.Color(23, 194, 157));

        DashboardButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DashboardButton.setText("Dashboard");
        DashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardButtonActionPerformed(evt);
            }
        });

        BookingHistoryButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BookingHistoryButton.setText("Booking history");
        BookingHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingHistoryButtonActionPerformed(evt);
            }
        });

        LogoutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/7124045_logout_icon(1).png"))); // NOI18N
        LogoutButton.setText("Logout");

        UserProfileLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-3296(2).png"))); // NOI18N
        UserProfileLabel.setText("jLabel11");

        UserNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UserNameLabel.setText("Ram Bahadur");

        javax.swing.GroupLayout DashboardMenuPanelLayout = new javax.swing.GroupLayout(DashboardMenuPanel);
        DashboardMenuPanel.setLayout(DashboardMenuPanelLayout);
        DashboardMenuPanelLayout.setHorizontalGroup(
            DashboardMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardMenuPanelLayout.createSequentialGroup()
                .addGroup(DashboardMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DashboardMenuPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(DashboardMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LogoutButton)
                            .addGroup(DashboardMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(DashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BookingHistoryButton))))
                    .addGroup(DashboardMenuPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(UserProfileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UserNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)))
                .addGap(51, 51, 51))
        );
        DashboardMenuPanelLayout.setVerticalGroup(
            DashboardMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardMenuPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(DashboardMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserProfileLabel)
                    .addComponent(UserNameLabel))
                .addGap(81, 81, 81)
                .addComponent(DashboardButton)
                .addGap(29, 29, 29)
                .addComponent(BookingHistoryButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addComponent(LogoutButton)
                .addGap(86, 86, 86))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(DashboardMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(AccomodationLabel)
                        .addGap(266, 266, 266)
                        .addComponent(AvailabilityLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SingleRoomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DoubleRoomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DeluxeRoomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ExecutiveSuitePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(LogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AccomodationLabel)
                            .addComponent(AvailabilityLabel))
                        .addGap(52, 52, 52)
                        .addComponent(SingleRoomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(DoubleRoomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(DeluxeRoomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(ExecutiveSuitePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(DashboardMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SingleRoomDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingleRoomDetailsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SingleRoomDetailsButtonActionPerformed

    private void DoubleRoomDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoubleRoomDetailsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoubleRoomDetailsButtonActionPerformed

    private void DeluxeRoomDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeluxeRoomDetailsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeluxeRoomDetailsButtonActionPerformed

    private void ExecutiveSuiteRoomDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExecutiveSuiteRoomDetailsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExecutiveSuiteRoomDetailsButtonActionPerformed

    private void DashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DashboardButtonActionPerformed

    private void BookingHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingHistoryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookingHistoryButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccomodationLabel;
    private javax.swing.JLabel AvailabilityLabel;
    private javax.swing.JButton BookingHistoryButton;
    private javax.swing.JLabel CheckInnLogoLabel;
    private javax.swing.JButton DashboardButton;
    private javax.swing.JPanel DashboardMenuPanel;
    private javax.swing.JButton DeluxeRoomDetailsButton;
    private javax.swing.JPanel DeluxeRoomPanel;
    private javax.swing.JButton DoubleRoomDetailsButton;
    private javax.swing.JPanel DoubleRoomPanel;
    private javax.swing.JPanel ExecutiveSuitePanel;
    private javax.swing.JButton ExecutiveSuiteRoomDetailsButton;
    private javax.swing.JPanel LogoPanel;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton SingleRoomDetailsButton;
    private javax.swing.JPanel SingleRoomPanel;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JLabel UserProfileLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

     public void addSingleRoomListener(ActionListener actionListener) {
        SingleRoomDetailsButton.addActionListener(actionListener);
    }

    public void addDoubleRoomListener(ActionListener actionListener) {
        DoubleRoomDetailsButton.addActionListener(actionListener);
    }

    public void addDeluxeRoomListener(ActionListener actionListener) {
        DeluxeRoomDetailsButton.addActionListener(actionListener);
    }

    public void addSuiteRoomListener(ActionListener actionListener) {
        ExecutiveSuiteRoomDetailsButton.addActionListener(actionListener);
    }

    public void addBookingHistoryListener(ActionListener actionListener) {
        BookingHistoryButton.addActionListener(actionListener);
    }

    public void addDashboardListener(ActionListener actionListener) {
        DashboardButton.addActionListener(actionListener);
    }

    public void addLogoutListener(ActionListener actionListener) {
        LogoutButton.addActionListener(actionListener);
    }

    public void setWelcomeMessage(String message) {
        javax.swing.JOptionPane.showMessageDialog(this, message, "Welcome ", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    public void setUserName(String firstName) {
        UserNameLabel.setText(firstName);
    }
}
