/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package checkinn.view;

import checkinn.model.MenuItem;
import java.util.Date;
import java.util.List;

/**
 *
 * @author risha
 */
public class InvoiceView extends javax.swing.JFrame {

    /**
     * Creates new form InvoiceView
     */
    public InvoiceView() {
        initComponents();
        setTitle("Invoice | CheckInn");
        setLocationRelativeTo(null);
            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

public void setInvoiceData(String roomType, String customerName, String fullName, Date checkIn, Date checkOut, List<MenuItem> menuItems, double totalPrice) {
    InvoiceRoomName.setText(roomType);
    ClientName.setText(customerName);
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd-MM-yyyy");
    InvoiceCheckIn.setText(checkIn != null ? sdf.format(checkIn) : "--");
    InvoiceCheckOut.setText(checkOut != null ? sdf.format(checkOut) : "--");
    StringBuilder menuList = new StringBuilder();
    for (MenuItem item : menuItems) {
        menuList.append(item.getItemName()).append(" - ").append(item.getPrice()).append("\n");
    }
    MenuItemsTextArea.setText(menuList.toString());
    InvoiceTotalPrice.setText("Rs. " + String.format("%.2f", totalPrice));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        InvoicePanel = new javax.swing.JPanel();
        LogoLabel = new javax.swing.JLabel();
        RoomTypeField = new javax.swing.JLabel();
        CheckInDateField = new javax.swing.JLabel();
        InvoiceCheckIn = new javax.swing.JLabel();
        CheckOutDateField = new javax.swing.JLabel();
        InvoiceCheckOut = new javax.swing.JLabel();
        MenuItemsField = new javax.swing.JLabel();
        InvoiceMenuItems = new javax.swing.JLabel();
        InvoiceRoomName = new javax.swing.JLabel();
        TotalPriceField = new javax.swing.JLabel();
        InvoiceTotalPrice = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ClientName = new javax.swing.JLabel();
        CloseInvoice = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MenuItemsTextArea = new javax.swing.JTextArea();

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);

        InvoicePanel.setBackground(new java.awt.Color(229, 224, 224));
        InvoicePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkinnlogo.png"))); // NOI18N
        LogoLabel.setText("jLabel2");

        RoomTypeField.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        RoomTypeField.setText("Room Type : ");

        CheckInDateField.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        CheckInDateField.setText("Check-In Date :");

        InvoiceCheckIn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        InvoiceCheckIn.setText("XX-XX-XXXX");

        CheckOutDateField.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        CheckOutDateField.setText("Check-Out Date :");

        InvoiceCheckOut.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        InvoiceCheckOut.setText("XX-XX-XXXX");

        MenuItemsField.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        MenuItemsField.setText("Menu Items :");

        InvoiceMenuItems.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        InvoiceRoomName.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        InvoiceRoomName.setText("<RoomName>");

        TotalPriceField.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        TotalPriceField.setText("Total Price : ");

        InvoiceTotalPrice.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        InvoiceTotalPrice.setText("Rs. XXXX.XX");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Invoice.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Client Information :");

        ClientName.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ClientName.setText("Name");

        CloseInvoice.setBackground(new java.awt.Color(61, 125, 125));
        CloseInvoice.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CloseInvoice.setForeground(new java.awt.Color(255, 255, 255));
        CloseInvoice.setText("Done");

        MenuItemsTextArea.setEditable(false);
        MenuItemsTextArea.setColumns(20);
        MenuItemsTextArea.setLineWrap(true);
        MenuItemsTextArea.setRows(5);
        MenuItemsTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(MenuItemsTextArea);

        javax.swing.GroupLayout InvoicePanelLayout = new javax.swing.GroupLayout(InvoicePanel);
        InvoicePanel.setLayout(InvoicePanelLayout);
        InvoicePanelLayout.setHorizontalGroup(
            InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InvoicePanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(InvoicePanelLayout.createSequentialGroup()
                        .addComponent(CheckInDateField)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(InvoicePanelLayout.createSequentialGroup()
                        .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckOutDateField)
                            .addComponent(MenuItemsField)
                            .addComponent(RoomTypeField)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InvoiceMenuItems)))
                .addGap(59, 59, 59))
            .addGroup(InvoicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InvoicePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(TotalPriceField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InvoiceTotalPrice)
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InvoicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 418, Short.MAX_VALUE)
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(InvoiceCheckIn)
                    .addComponent(InvoiceRoomName)
                    .addComponent(InvoiceCheckOut)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InvoicePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CloseInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        InvoicePanelLayout.setVerticalGroup(
            InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvoicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoLabel)
                    .addComponent(jLabel1))
                .addGap(42, 42, 42)
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoomTypeField)
                    .addComponent(InvoiceRoomName))
                .addGap(44, 44, 44)
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ClientName))
                .addGap(44, 44, 44)
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckInDateField)
                    .addComponent(InvoiceCheckIn))
                .addGap(44, 44, 44)
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckOutDateField)
                    .addComponent(InvoiceCheckOut))
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InvoicePanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MenuItemsField)
                            .addComponent(InvoiceMenuItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(79, 79, 79))
                    .addGroup(InvoicePanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 22, Short.MAX_VALUE)
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalPriceField)
                    .addComponent(InvoiceTotalPrice))
                .addGap(58, 58, 58)
                .addComponent(CloseInvoice)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InvoicePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InvoicePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InvoiceView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CheckInDateField;
    private javax.swing.JLabel CheckOutDateField;
    private javax.swing.JLabel ClientName;
    private javax.swing.JButton CloseInvoice;
    private javax.swing.JLabel InvoiceCheckIn;
    private javax.swing.JLabel InvoiceCheckOut;
    private javax.swing.JLabel InvoiceMenuItems;
    private javax.swing.JPanel InvoicePanel;
    private javax.swing.JLabel InvoiceRoomName;
    private javax.swing.JLabel InvoiceTotalPrice;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JLabel MenuItemsField;
    private javax.swing.JTextArea MenuItemsTextArea;
    private javax.swing.JLabel RoomTypeField;
    private javax.swing.JLabel TotalPriceField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getCloseInvoiceButton() {
    return CloseInvoice;
}

}